# Generated by Django 4.2 on 2023-05-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('truckid', models.AutoField(primary_key=True, serialize=False)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('wh_id', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('IDLE', 'Idle'), ('TRAVELING', 'Traveling'), ('ARRIVEWH', 'ArriveWarehouse'), ('LOADING', 'Loading'), ('DELIVERING', 'Delivering')], default='IDLE', max_length=100)),
            ],
            options={
                'db_table': 'truck',
            },
        ),
        migrations.CreateModel(
            name='UpsPackage',
            fields=[
                ('packageid', models.AutoField(primary_key=True, serialize=False)),
                ('amzpackageid', models.BigIntegerField(default=0)),
                ('truckid', models.IntegerField(default=0)),
                ('userid', models.IntegerField(default=0)),
                ('updatetime', models.CharField(max_length=100)),
                ('detail', models.CharField(default='', max_length=1000)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('status', models.CharField(choices=[('packed', 'packed'), ('loading', 'loading'), ('loaded', 'loaded'), ('delivering', 'delivering'), ('delivered', 'delivered')], default='packed', max_length=100)),
            ],
            options={
                'db_table': 'package',
            },
        ),
    ]
